# appveyor.yml
build: off

clone_folder: c:\gopath\src\github.com\pathaugen\interview-toyota

environment:
  GOPATH: c:\gopath

stack: go 1.10.3

before_test:
  - go vet ./...

test_script:
  - go test ./...
